
spring:
  mail:
    host: smtp.gmail.com
    username: afrozreshma56@gmail.com
    password: nfqk mzpy evoe dkty
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          
server.port: 8081